apiVersion: v1
kind: Service
metadata:
  name: worker
  namespace: realstateos
  labels:
    app: worker
    app.kubernetes.io/name: worker
    app.kubernetes.io/part-of: realstateos
spec:
  type: ClusterIP
  selector:
    app: worker
  ports:
    - name: http
      port: 8081
      targetPort: http
      protocol: TCP
