apiVersion: v1
kind: Service
metadata:
  name: web
  namespace: realstateos
  labels:
    app: web
    app.kubernetes.io/name: web
    app.kubernetes.io/part-of: realstateos
spec:
  type: ClusterIP
  selector:
    app: web
  ports:
    - name: http
      port: 3000
      targetPort: http
      protocol: TCP
