#!/usr/bin/env python3
"""
SLO Validation — Real Estate OS Load Tests
==========================================

Reads the CSV stats generated by Locust (tests/load/results/stats_stats.csv)
and validates against the agreed SLO targets:

    Metric          SLO
    ──────────────  ──────────────────
    p95 latency     < 200 ms
    Error rate      < 1 %
    Avg throughput  > 50 req/s         (sanity check — not a hard SLO)

Exit codes:
    0  All SLOs met
    1  One or more SLOs breached (blocks CI)

Usage:
    # After a locust run with --csv tests/load/results/stats:
    python tests/load/slo_check.py

    # Custom CSV path:
    python tests/load/slo_check.py --csv path/to/stats_stats.csv

    # Per-endpoint breakdown in addition to aggregate:
    python tests/load/slo_check.py --verbose
"""
from __future__ import annotations

import argparse
import csv
import sys
from dataclasses import dataclass
from pathlib import Path


# ─── SLO targets ─────────────────────────────────────────────────────────────

SLO_P95_MS: float = 200.0   # milliseconds
SLO_ERROR_RATE: float = 1.0  # percent
MIN_THROUGHPUT_RPS: float = 50.0  # req/s sanity check


# ─── Data model ──────────────────────────────────────────────────────────────


@dataclass
class EndpointStats:
    name: str
    request_count: int
    failure_count: int
    median_ms: float
    p95_ms: float
    p99_ms: float
    avg_ms: float
    rps: float

    @property
    def error_rate_pct(self) -> float:
        if self.request_count == 0:
            return 0.0
        return self.failure_count / self.request_count * 100

    @property
    def slo_p95_ok(self) -> bool:
        return self.p95_ms < SLO_P95_MS

    @property
    def slo_error_rate_ok(self) -> bool:
        return self.error_rate_pct < SLO_ERROR_RATE


# ─── CSV parser ──────────────────────────────────────────────────────────────


def _safe_float(value: str, default: float = 0.0) -> float:
    try:
        return float(value)
    except (ValueError, TypeError):
        return default


def _safe_int(value: str, default: int = 0) -> int:
    try:
        return int(float(value))
    except (ValueError, TypeError):
        return default


def parse_locust_csv(csv_path: Path) -> list[EndpointStats]:
    """
    Parse Locust stats CSV.

    Locust generates two CSV files:
      <prefix>_stats.csv       — per-endpoint aggregates
      <prefix>_stats_history.csv — time-series

    We read _stats.csv (or the path as-is if it ends with .csv).
    """
    if not csv_path.exists():
        # Try adding _stats.csv suffix
        candidate = csv_path.parent / (csv_path.name.rstrip("/") + "_stats.csv")
        if candidate.exists():
            csv_path = candidate
        else:
            raise FileNotFoundError(f"CSV not found: {csv_path}  (also tried {candidate})")

    stats: list[EndpointStats] = []
    with csv_path.open(encoding="utf-8", newline="") as fh:
        reader = csv.DictReader(fh)
        for row in reader:
            name = row.get("Name", "").strip()
            if not name:
                continue
            stats.append(
                EndpointStats(
                    name=name,
                    request_count=_safe_int(row.get("Request Count", "0")),
                    failure_count=_safe_int(row.get("Failure Count", "0")),
                    median_ms=_safe_float(row.get("50%", "0")),
                    p95_ms=_safe_float(row.get("95%", "0")),
                    p99_ms=_safe_float(row.get("99%", "0")),
                    avg_ms=_safe_float(row.get("Average (ms)", "0")),
                    rps=_safe_float(row.get("Requests/s", "0")),
                )
            )
    return stats


# ─── Reporter ─────────────────────────────────────────────────────────────────


def _print_row(label: str, value: str, ok: bool | None = None) -> None:
    status = ""
    if ok is True:
        status = " [PASS]"
    elif ok is False:
        status = " [FAIL]"
    print(f"  {label:<35} {value}{status}")


def check_slos(stats: list[EndpointStats], verbose: bool = False) -> bool:
    """
    Validate aggregate (Aggregated row) and per-endpoint SLOs.

    Returns True if all SLOs pass.
    """
    # Find aggregate row
    aggregate = next((s for s in stats if s.name.lower() in ("aggregated", "total")), None)
    if aggregate is None and stats:
        # Sum up manually
        total_reqs = sum(s.request_count for s in stats)
        total_fails = sum(s.failure_count for s in stats)
        max_p95 = max((s.p95_ms for s in stats), default=0.0)
        total_rps = sum(s.rps for s in stats)
        aggregate = EndpointStats(
            name="(computed aggregate)",
            request_count=total_reqs,
            failure_count=total_fails,
            median_ms=0.0,
            p95_ms=max_p95,
            p99_ms=0.0,
            avg_ms=0.0,
            rps=total_rps,
        )

    if aggregate is None:
        print("ERROR: No stats rows found in CSV — was the test run long enough?")
        return False

    print()
    print("=" * 60)
    print("SLO VALIDATION REPORT")
    print("=" * 60)
    print()
    print(f"  Source: {aggregate.name}")
    print(f"  Total requests : {aggregate.request_count:,}")
    print(f"  Total failures : {aggregate.failure_count:,}")
    print()

    all_pass = True

    # ── Aggregate SLO checks ──
    print("Aggregate SLOs:")
    p95_ok = aggregate.p95_ms < SLO_P95_MS
    err_ok = aggregate.error_rate_pct < SLO_ERROR_RATE
    tps_ok = aggregate.rps >= MIN_THROUGHPUT_RPS

    _print_row(
        f"p95 latency (< {SLO_P95_MS:.0f} ms)",
        f"{aggregate.p95_ms:.0f} ms",
        p95_ok,
    )
    _print_row(
        f"Error rate (< {SLO_ERROR_RATE:.1f}%)",
        f"{aggregate.error_rate_pct:.2f}%",
        err_ok,
    )
    _print_row(
        f"Throughput (>= {MIN_THROUGHPUT_RPS:.0f} req/s)",
        f"{aggregate.rps:.1f} req/s",
        tps_ok,
    )

    if not p95_ok:
        all_pass = False
        print(f"\n  [FAIL] p95 {aggregate.p95_ms:.0f}ms exceeds {SLO_P95_MS:.0f}ms target")
        print("         Likely causes: DB query slowness, N+1 queries, missing indexes")
        print("         Action: run EXPLAIN ANALYZE on slow queries, check Redis hit rate")

    if not err_ok:
        all_pass = False
        print(f"\n  [FAIL] Error rate {aggregate.error_rate_pct:.2f}% exceeds {SLO_ERROR_RATE:.1f}% target")
        print("         Check: Locust HTML report for failure reasons")
        print("         Common causes: 422 validation errors, 500 server errors, timeouts")

    if not tps_ok:
        # Throughput warning is not a hard SLO breach
        print(f"\n  [WARN] Throughput {aggregate.rps:.1f} req/s below {MIN_THROUGHPUT_RPS:.0f} req/s sanity check")
        print("         Test may not have run long enough or spawn-rate was too low")

    # ── Per-endpoint breakdown ──
    if verbose:
        print()
        print("Per-endpoint breakdown:")
        print(f"  {'Endpoint':<50} {'Reqs':>6} {'p95':>8} {'Err%':>6}")
        print(f"  {'-'*50} {'-'*6} {'-'*8} {'-'*6}")
        for ep in sorted(stats, key=lambda s: s.p95_ms, reverse=True):
            if ep.name.lower() in ("aggregated", "total"):
                continue
            flag = ""
            if not ep.slo_p95_ok:
                flag += " [p95!]"
            if not ep.slo_error_rate_ok:
                flag += " [err!]"
            print(
                f"  {ep.name:<50} {ep.request_count:>6,} {ep.p95_ms:>7.0f}ms "
                f"{ep.error_rate_pct:>5.1f}%{flag}"
            )

    print()
    print("=" * 60)
    if all_pass:
        print("RESULT: ALL SLOs MET")
    else:
        print("RESULT: SLO BREACH — fix issues before deploying to production")
    print("=" * 60)
    print()

    return all_pass


# ─── CLI ──────────────────────────────────────────────────────────────────────


def main() -> int:
    parser = argparse.ArgumentParser(description="Real Estate OS SLO validator")
    parser.add_argument(
        "--csv",
        default="tests/load/results/stats_stats.csv",
        help="Path to Locust *_stats.csv file (default: tests/load/results/stats_stats.csv)",
    )
    parser.add_argument(
        "--verbose",
        action="store_true",
        help="Show per-endpoint breakdown in addition to aggregate",
    )
    args = parser.parse_args()

    csv_path = Path(args.csv)
    try:
        stats = parse_locust_csv(csv_path)
    except FileNotFoundError as exc:
        print(f"\nERROR: {exc}")
        print("Run a Locust test first: locust --config tests/load/locust.conf")
        return 1

    passed = check_slos(stats, verbose=args.verbose)
    return 0 if passed else 1


if __name__ == "__main__":
    sys.exit(main())
