apiVersion: v1
kind: Service
metadata:
  name: api-node
  namespace: realstateos
  labels:
    app: api-node
    app.kubernetes.io/name: api-node
    app.kubernetes.io/part-of: realstateos
spec:
  type: ClusterIP
  selector:
    app: api-node
  ports:
    - name: http
      port: 8082
      targetPort: http
      protocol: TCP
